// Bundled recorded runs for the offline interview fallback (P3-03).
// Generated by `uv run python -m agent.replay.export_ui_bundle`.
import lena from "./replay/lena.json";
import marco from "./replay/marco.json";
import sanctionTest from "./replay/sanction_test.json";
import type { AgentCard, AuditEvent, Escalation, RuleInfo, SessionSnapshot } from "./types";

export interface ReplayBundle {
  persona: string;
  card: AgentCard;
  events: AuditEvent[];
  snapshot: SessionSnapshot;
  escalations: Escalation[];
  rules: RuleInfo[];
}

export const BUNDLES: Record<string, ReplayBundle> = {
  lena: lena as unknown as ReplayBundle,
  marco: marco as unknown as ReplayBundle,
  sanction_test: sanctionTest as unknown as ReplayBundle,
};
